version: "3.3"
services:
  api:
    build: ./API
    container_name: ft_transcendence-API
    env_file:
      - ./.env
    # volumes:
    #   - "uploads:/app/uploads"
    links:
      - database
    depends_on:
      - database
    restart: unless-stopped

  database:
    image: postgres:13.3
    container_name: ft_transcendence-database
    volumes:
      - "database:/var/lib/postgresql/data"
    env_file:
      - ./.env
    restart: unless-stopped

  proxy:
    image: nginx:1.19
    container_name: ft_transcendence-proxy
    volumes:
      - "./nginx.conf:/etc/nginx/conf.d/default.conf"
    links:
      - api
    depends_on:
      - api
    ports:
      - "80:80"
    restart: unless-stopped

volumes:
  database:
  # uploads: