version: "3.3"
services:
  api:
    build: ./API
    container_name: ft_transcendence-API
    env_file:
      - ./.env
    ports:
      - "5432:5432"
      - "3000:3000" # temporary for testing tchat
    volumes:
      - ./upload/:/upload
    links:
      - database
    depends_on:
      - database
    restart: unless-stopped

  database:
    image: postgres:13.3
    container_name: ft_transcendence-database
    volumes:
      - "database:/var/lib/postgresql/data"
    env_file:
      - ./.env
    restart: unless-stopped

  pgadmin:
    container_name: ft_transcendence-pgadmin
    image: dpage/pgadmin4
    restart: always
    links:
      - database
    depends_on:
      - database
    environment:
      PGADMIN_DEFAULT_EMAIL: jode-vri@student.42.fr
      PGADMIN_DEFAULT_PASSWORD: toor
    ports:
      - "5050:80"

  proxy:
    build: ./nginx
    container_name: ft_transcendence-proxy
    links:
      - api
    depends_on:
      - api
    ports:
      - "8080:80"
    restart: unless-stopped

volumes:
  database:
  # uploads: